# This is for dev
version: '3'
services:
  stoxygen-downloader:
    build:
        context: .devcontainer
        dockerfile: Dockerfile
        args:
          VARIANT: "11"
          INSTALL_MAVEN: "true"
          INSTALL_GRADLE: "false"
          INSTALL_NODE: "false"
          NODE_VERSION: "lts/*"
    environment:
      SPRING_PROFILES_ACTIVE: dev,websocket
    networks:
      - stoxygen_downloader
  sto2-rabbitmq:
    image: rabbitmq:3.7.8-management
    networks: 
      - stoxygen_downloader
  sto2-psql:
    image: postgres:10.6
    environment:
      POSTGRES_USER: sto2-downloader
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sto2_downloader
    networks:
      - stoxygen_downloader
  pgadmin4:
    image: dpage/pgadmin4:4.5
    ports:
      - 8082:80
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    networks:
      - stoxygen_downloader
networks:
  stoxygen_downloader:
    ipam:
      config:
        - subnet: 100.64.1.0/24